# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0efdaba73c9743a175a593d500cbd607c2223e82e4998010dcbc4cb3860026e90df9f62b8257690cf5bf24257b09278a8e8a08e491d0a8616f09209cfc955842

test:
  secret_key_base: 841b628bf03f1fe39e270e29b12377a2c8ea65c62389532bbc7718edca28a010b562dae268bb708a4490dd37fab7614997c5bd7bdf595e4a6e73f01c2c258aa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
